name: 01 Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test || true  # Fortfahren, auch wenn Tests fehlschlagen

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: target/*.jar

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # immer ausführen, auch wenn Tests fehlschlagen
        with:
          report_paths: '**/target/surefire-reports/*.xml'
